### ISSUE TITLE
如何升级代码版本而不影响到现有docker中mysql存储的数据？

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/deeptest#47]
能否提供一下升级步骤呢？

**Comment by aaronchen2k** [comment]
已经给MySQL和SpringBoot容器加上版本号，目前为1.0.10。

**_Once you create and start containers by using "docker-compose up" command, next time you should use "docker-compose start|stop" to avoid to docker-compose re-creating the container after the remote image changed, which will cause data-losing._**

当再次使用docker-compose up命令，尝试升级前，请务必备份你的数据，升级成功后恢复整个DB，然后运行版本升级配套的SQL脚本。

我这边目前会做得是：

- 每次容器启动时，MySQL容器中的setup.sh脚本，会判断数据是否已初始化，不会覆盖现有的数据；
- 后续升级，比如从1.0.10到1.0.20，我会给出升级指南，包括数据库的升级脚本；
- 升级与否、升级到什么版本，由docker-compose.xml文件里的两个镜像版本号的变化来决定，请进一步确认。

**Comment by bitlin** [comment]
老铁什么时候能给出升级指南呀？

**Comment by aaronchen2k** [comment]
@bitlin 从1.0版本开始，数据库基本没变，请微信联系协助。
