### ISSUE TITLE
有个需求场景，测试筛选一部分测试用例给开发，让他们在提测前做自测

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/deeptest#51]
实现用例筛选功能，可筛选出可用于开发人员自测的用例。

再深度思考的话，可以添加一个模块，规范开发自测流程，这里有个开源的实现：https://github.com/youzan/bugCatcher

**Comment by aaronchen2k** [comment]
自测用例可以建一个测试集，每次自测时根据测试集创建任务，分配给开发。
有关自测质量，可考虑在testplan->testtask层面做一个检查功能，用于“测试检查开发自测”或“主管检查任务执行”情况。这样可不限于某个特定的流程。
